<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.16">
  <POU Name="FB_instancePath" Id="{819d84ae-5755-4f81-b04d-000bd20f24c0}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'reflection'} 
FUNCTION_BLOCK FB_instancePath 
VAR 
    {attribute 'instance-path'} 
    {attribute 'noinit'} 
    sPath : STRING; 
END_VAR 
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_instancePath">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>